name: mcMMOLevel2PEXPromote
main: com.github.planethouki.mcmmolevel2pexpromote.McpexPlugin
version: 0.0.1
depend: [mcMMO, PermissionsEx]
commands:
  mcpex:
    usage: |
      /<command> version - show version
      /<command> reload - reload config
      /<command> show - show config